export const COMPLETE_START = 'COMPLETE_START';
export const COMPLETE_SUCCEED = 'COMPLETE_SUCCEED';
export const COMPLETE_FAIL = 'COMPLETE_FAIL';
export const CREATE_PNG_START = 'CREATE_PNG_START';
export const CREATE_PNG_SUCCEED = 'CREATE_PNG_SUCCEED';
export const CREATE_PNG_FAIL = 'CREATE_PNG_FAIL';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_BG_IMAGE_URL = 'CHANGE_BG_IMAGE_URL';
